.TH TOX-DHT-BOOTSTRAP 1 "October 2014"

.SH NAME
tox-DHT_bootstrap - bootstrap to the tox network

.SH SYNOPSIS
.B tox-DHT_bootstrap \fI[ADDRESS]\fR [\fIPORT\fR] [\fIKEY\fR]

.SH DESCRIPTION
To be able to connect to others, Tox needs to connect to a DHT node first. All
DHT nodes are connected to each other, and since everyone is connected to at
least one DHT node, you can connect to others one way or the other.

.PP
Change ADDRESS, PORT, and KEY to any running DHT node.

.SH SEE ALSO:
.br
\fBtox-bootstrapd\fR(1)
.br

.SH LINKS:
.br
.B Wiki:
https://wiki.tox.im/Nodes https://wiki.tox.im/Run_a_node
.br


.SH AUTHOR
This manual page was written by kytv <killyourtv@i2pmail.org> for the Debian system (but may be used by others).
.PP
Permission is granted to copy, distribute and/or modify this document under the
terms of the GNU General Public License, Version 2 or any later version
published by the Free Software Foundation
.PP
On Debian systems, the complete text of the GNU General Public License can be
found in /usr/share/common-licenses/GPL.
